[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.json", "php82Extensions.curl", "php82Extensions.openssl", "nginx"]

[phases.build]
cmds = []

[start]
cmd = "bash start.sh"
