[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mysqli", "php82Extensions.mbstring", "php82Extensions.json", "php82Extensions.curl", "php82Extensions.openssl", "nginx"]

[phases.build]
cmds = [
  "php82 -r \"echo extension_loaded('pdo_mysql') ? 'pdo_mysql OK' : 'pdo_mysql MISSING'; echo PHP_EOL;\""
]

[start]
cmd = "bash start.sh"
