-- ============================================================
-- HustleKingdom — Roadmaps seed
-- Add roadmaps table and seed 3 roadmaps from index.html
-- ============================================================

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `roadmaps` (
  `id`         INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hustle_id`  VARCHAR(191) NOT NULL,
  `name`       VARCHAR(150) NOT NULL,
  `emoji`      VARCHAR(10)  NOT NULL DEFAULT '🗺️',
  `summary`    TEXT         DEFAULT NULL,
  `duration`   VARCHAR(100) DEFAULT NULL,
  `phases`     JSON         DEFAULT NULL,
  `created_at` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hustle_roadmap` (`hustle_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `roadmaps` (`hustle_id`, `name`, `emoji`, `summary`, `duration`, `phases`) VALUES
('freelance-writing', 'Freelance Writing', '✍️', 'Go from zero to ₦50k/month writing online — no degree required.', '4–8 weeks to first ₦10k', '[{"num": 1, "title": "Foundation", "time": "Week 1\\u20132", "steps": [{"icon": "\\ud83d\\udcda", "name": "Learn the craft", "desc": "Study the difference between SEO writing, copywriting, and content writing. Understand what clients actually pay for.", "tools": ["YouTube: Alex Cattoni", "HubSpot Blog Academy (free)"]}, {"icon": "\\u270d\\ufe0f", "name": "Write 5 sample articles", "desc": "Pick a niche you know: finance, health, tech, relationships. Write 800\\u20131200 word articles at that quality level.", "tools": ["Google Docs", "Grammarly (free)", "Hemingway App"]}]}, {"num": 2, "title": "Setup & First Clients", "time": "Week 2\\u20133", "steps": [{"icon": "\\ud83c\\udf10", "name": "Create Upwork & Fiverr profiles", "desc": "Professional photo, strong bio, 3 gig packages on Fiverr. Complete 100% profile on Upwork.", "tools": ["Fiverr", "Upwork", "LinkedIn"]}, {"icon": "\\ud83d\\udcec", "name": "Send 15 pitches daily", "desc": "Custom proposal per client. Reference their specific project. Show you read their brief. Quality beats quantity.", "tools": ["Upwork", "Cold Email via Gmail"]}]}, {"num": 3, "title": "Build Reputation", "time": "Week 3\\u20136", "steps": [{"icon": "\\u2b50", "name": "Deliver 5-star quality", "desc": "Always deliver before deadline. Always ask \\"what would make this perfect?\\" Build a 5.0 Fiverr rating.", "tools": ["Google Docs", "Grammarly", "Copyscape"]}, {"icon": "\\ud83d\\udcb0", "name": "Raise your rates", "desc": "Every 5 positive reviews = rate increase of 20\\u201330%. Track your hourly rate and increase strategically.", "tools": ["Fiverr Analytics", "Upwork Rate Tracker"]}]}, {"num": 4, "title": "Scale to \\u20a6100k/month", "time": "Month 2+", "steps": [{"icon": "\\ud83d\\udd01", "name": "Build retainer clients", "desc": "Propose monthly packages to best clients: \\"10 articles/month for $X.\\" Stable income beats one-off gigs.", "tools": ["Notion", "Calendly", "Stripe"]}, {"icon": "\\ud83d\\udce7", "name": "Start an email list", "desc": "Create a free newsletter. Every subscriber is a potential direct client. Bypass Fiverr/Upwork 20% fees.", "tools": ["ConvertKit (free)", "Substack", "Beehiiv"]}]}]'),
('social-media-mgmt', 'Social Media Management', '📊', 'Build a social media agency from your bedroom — earn ₦200k/month managing client accounts.', '2–4 weeks to first client', '[{"num": 1, "title": "Skill Building", "time": "Week 1", "steps": [{"icon": "\\ud83d\\udcda", "name": "Learn platform algorithms", "desc": "Study TikTok, Instagram, and Facebook algorithms deeply. Understand what content gets pushed and why.", "tools": ["YouTube: HubSpot Marketing", "Meta Blueprint (free)", "TikTok Creator Academy"]}, {"icon": "\\ud83c\\udfa8", "name": "Master content creation", "desc": "Learn to create scroll-stopping graphics, Reels, and captions. Practice daily on your own account.", "tools": ["Canva", "CapCut", "Adobe Express"]}]}, {"num": 2, "title": "Portfolio & Positioning", "time": "Week 1\\u20132", "steps": [{"icon": "\\ud83d\\udcf1", "name": "Build 2 mock brand pages", "desc": "Create fake brands and manage them for 2 weeks. This becomes your portfolio when pitching real clients.", "tools": ["Instagram", "TikTok", "Buffer"]}, {"icon": "\\ud83d\\udcbc", "name": "Define your niche", "desc": "SMMs who specialize earn 3x more. Pick: restaurants, fashion, real estate, or health/beauty.", "tools": ["Competitor analysis on Instagram"]}]}, {"num": 3, "title": "Land First Clients", "time": "Week 2\\u20133", "steps": [{"icon": "\\ud83c\\udfaf", "name": "Cold DM 30 businesses/day", "desc": "Find businesses with poor social media. Send a specific critique + offer to fix it for free for 30 days.", "tools": ["Instagram DM", "WhatsApp", "LinkedIn"]}, {"icon": "\\ud83e\\udd1d", "name": "1 month free trial strategy", "desc": "Offer 30 days free to first 2 clients. Results speak louder than pitches. Get testimonial + case study.", "tools": ["Meta Business Suite", "Canva", "Buffer"]}]}, {"num": 4, "title": "Systems & Scale", "time": "Month 2+", "steps": [{"icon": "\\u2699\\ufe0f", "name": "Build content systems", "desc": "Create content calendars, template libraries, and approval workflows. Manage 5+ clients without burning out.", "tools": ["Notion", "Buffer", "Later", "Google Drive"]}, {"icon": "\\ud83d\\udcc8", "name": "Raise prices + hire", "desc": "At \\u20a6200k/month+ revenue, hire a junior content creator. You become the strategist/account manager.", "tools": ["Upwork (hiring)", "Slack", "Trello"]}]}]'),
('crypto-p2p', 'Crypto P2P Trading', '₿', 'Build a P2P trading operation — from ₦50k float to ₦1m/month.', 'Start earning same day', '[{"num": 1, "title": "Setup & Education", "time": "Day 1\\u20133", "steps": [{"icon": "\\ud83c\\udf93", "name": "Understand P2P mechanics", "desc": "Learn how spreads work, how to identify arbitrage opportunities between exchanges, and how to protect yourself from scammers.", "tools": ["YouTube: Crypto P2P Nigeria", "Binance Academy", "Reddit r/BinanceP2P"]}, {"icon": "\\ud83d\\udd10", "name": "Create verified accounts", "desc": "KYC-verify on Binance, Bybit, and Noones. Use your real info \\u2014 2FA on everything. Security is non-negotiable.", "tools": ["Binance", "Bybit", "Noones"]}]}, {"num": 2, "title": "First Trades", "time": "Week 1", "steps": [{"icon": "\\ud83d\\udcb0", "name": "Start with small float", "desc": "Begin with \\u20a630k\\u2013\\u20a650k. Execute 10\\u201320 small trades to understand the flow before scaling.", "tools": ["Binance P2P", "Bybit P2P"]}, {"icon": "\\u2b50", "name": "Build trade reputation", "desc": "Complete trades fast, communicate professionally. Rating is everything on P2P \\u2014 protect it fiercely.", "tools": ["Binance Merchant Program"]}]}, {"num": 3, "title": "Scale the Float", "time": "Month 1\\u20133", "steps": [{"icon": "\\ud83d\\udcc8", "name": "Compound profits", "desc": "Reinvest 80% of daily profits into float. A \\u20a650k float at \\u20a65k/day profit grows to \\u20a6200k in 30 days.", "tools": ["Spreadsheet tracking", "Binance Earn (idle float)"]}, {"icon": "\\ud83d\\udd04", "name": "Multi-exchange arbitrage", "desc": "Find rate differences between Binance, Bybit, Noones, and Paxful. Buy cheap on one, sell higher on another.", "tools": ["Multiple exchange accounts", "Rate comparison manually"]}]}, {"num": 4, "title": "Full Operation", "time": "Month 3+", "steps": [{"icon": "\\ud83c\\udfe2", "name": "Become a verified merchant", "desc": "Apply for Binance/Bybit Merchant status. Higher trust = more customers = better spread capture.", "tools": ["Binance Merchant Program", "Bybit Pro"]}, {"icon": "\\ud83d\\udc65", "name": "Build a trading team", "desc": "Hire 1\\u20132 people to handle trades while you manage operations. This is how \\u20a61m+/month becomes achievable.", "tools": ["WhatsApp coordination", "Float management system"]}]}]');